"""add maintenance_components catalog

Revision ID: 19f5ee674319
Revises: aacbed75e3de
Create Date: 2026-07-08 23:17:41.567913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.seeds.maintenance_components import COMPONENTS


# revision identifiers, used by Alembic.
revision: str = '19f5ee674319'
down_revision: Union[str, Sequence[str], None] = 'aacbed75e3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('default_interval_km', sa.Integer(), nullable=True),
    sa.Column('default_interval_months', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###

    components_table = sa.table(
        "maintenance_components",
        sa.column("name", sa.String),
        sa.column("category", sa.String),
        sa.column("default_interval_km", sa.Integer),
        sa.column("default_interval_months", sa.Integer),
        sa.column("notes", sa.Text),
    )
    op.bulk_insert(
        components_table,
        [
            {
                "name": name,
                "category": category,
                "default_interval_km": km,
                "default_interval_months": months,
                "notes": notes,
            }
            for name, category, km, months, notes in COMPONENTS
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_components')
    # ### end Alembic commands ###
