"""add catalog_makes and catalog_models

Revision ID: 8b19094b857b
Revises: fe2184c9d622
Create Date: 2026-07-08 18:08:55.379322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b19094b857b'
down_revision: Union[str, Sequence[str], None] = 'fe2184c9d622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_makes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_makes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_makes_name'), ['name'], unique=True)

    op.create_table('catalog_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['catalog_makes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make_id', 'name', name='uq_catalog_model_make_name')
    )
    with op.batch_alter_table('catalog_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_models_make_id'), ['make_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_models_make_id'))

    op.drop_table('catalog_models')
    with op.batch_alter_table('catalog_makes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_makes_name'))

    op.drop_table('catalog_makes')
    # ### end Alembic commands ###
