"""add drivers and legal_documents (papeles)

Revision ID: aacbed75e3de
Revises: 8b19094b857b
Create Date: 2026-07-08 19:03:15.885630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacbed75e3de'
down_revision: Union[str, Sequence[str], None] = '8b19094b857b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('license_class', sa.String(length=20), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_user_id'), ['user_id'], unique=False)

    op.create_table('legal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=60), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'doc_type', name='uq_legal_document_vehicle_type')
    )
    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_documents_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_documents_vehicle_id'))

    op.drop_table('legal_documents')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_user_id'))

    op.drop_table('drivers')
    # ### end Alembic commands ###
