"""add service_records and service_files

Revision ID: fe2184c9d622
Revises: 361154c5d5a0
Create Date: 2026-07-08 17:44:38.371781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2184c9d622'
down_revision: Union[str, Sequence[str], None] = '361154c5d5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=120), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('workshop', sa.String(length=160), nullable=True),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_records_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('service_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_record_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_files_service_record_id'), ['service_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_files_service_record_id'))

    op.drop_table('service_files')
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_records_vehicle_id'))

    op.drop_table('service_records')
    # ### end Alembic commands ###
